# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Omer\Dropbox\Project\SSVEP v2.4/UI\frmMain.ui'
#
# Created: Wed Dec 09 19:53:21 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 617)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 617))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 617))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Cube = QtGui.QWidget()
        self.tab_Cube.setObjectName(_fromUtf8("tab_Cube"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_Cube)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MyCube = MyQGLWidget(self.tab_Cube)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MyCube.sizePolicy().hasHeightForWidth())
        self.MyCube.setSizePolicy(sizePolicy)
        self.MyCube.setMinimumSize(QtCore.QSize(500, 500))
        self.MyCube.setObjectName(_fromUtf8("MyCube"))
        self.horizontalLayout.addWidget(self.MyCube)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.tab_Cube)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.speedSlider = QtGui.QSlider(self.tab_Cube)
        self.speedSlider.setMinimum(1)
        self.speedSlider.setMaximum(100)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName(_fromUtf8("speedSlider"))
        self.verticalLayout_2.addWidget(self.speedSlider)
        self.pushButton_Spin = QtGui.QPushButton(self.tab_Cube)
        self.pushButton_Spin.setCheckable(True)
        self.pushButton_Spin.setObjectName(_fromUtf8("pushButton_Spin"))
        self.verticalLayout_2.addWidget(self.pushButton_Spin)
        self.pushButton_X = QtGui.QPushButton(self.tab_Cube)
        self.pushButton_X.setCheckable(True)
        self.pushButton_X.setObjectName(_fromUtf8("pushButton_X"))
        self.verticalLayout_2.addWidget(self.pushButton_X)
        self.pushButton_Y = QtGui.QPushButton(self.tab_Cube)
        self.pushButton_Y.setCheckable(True)
        self.pushButton_Y.setObjectName(_fromUtf8("pushButton_Y"))
        self.verticalLayout_2.addWidget(self.pushButton_Y)
        self.pushButton_Z = QtGui.QPushButton(self.tab_Cube)
        self.pushButton_Z.setCheckable(True)
        self.pushButton_Z.setObjectName(_fromUtf8("pushButton_Z"))
        self.verticalLayout_2.addWidget(self.pushButton_Z)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_Cube, _fromUtf8(""))
        self.tab_Electrodes = QtGui.QWidget()
        self.tab_Electrodes.setObjectName(_fromUtf8("tab_Electrodes"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_Electrodes)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.MyElectrodeMap = ElectrodeMap(self.tab_Electrodes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MyElectrodeMap.sizePolicy().hasHeightForWidth())
        self.MyElectrodeMap.setSizePolicy(sizePolicy)
        self.MyElectrodeMap.setMinimumSize(QtCore.QSize(500, 500))
        self.MyElectrodeMap.setBaseSize(QtCore.QSize(0, 0))
        self.MyElectrodeMap.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.TextAntialiasing)
        self.MyElectrodeMap.setObjectName(_fromUtf8("MyElectrodeMap"))
        self.horizontalLayout_2.addWidget(self.MyElectrodeMap)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.tab_Electrodes)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_Electrodes, _fromUtf8(""))
        self.tab_EEG = QtGui.QWidget()
        self.tab_EEG.setObjectName(_fromUtf8("tab_EEG"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_EEG)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.MyEEGTab = EEGTab(self.tab_EEG)
        self.MyEEGTab.setObjectName(_fromUtf8("MyEEGTab"))
        self.horizontalLayout_3.addWidget(self.MyEEGTab)
        self.tabWidget.addTab(self.tab_EEG, _fromUtf8(""))
        self.tab_SSVEP = QtGui.QWidget()
        self.tab_SSVEP.setObjectName(_fromUtf8("tab_SSVEP"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_SSVEP)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.mySSVEPTab = SSVEPTab(self.tab_SSVEP)
        self.mySSVEPTab.setObjectName(_fromUtf8("mySSVEPTab"))
        self.horizontalLayout_8.addWidget(self.mySSVEPTab)
        self.tabWidget.addTab(self.tab_SSVEP, _fromUtf8(""))
        self.tab_P300_Ring = QtGui.QWidget()
        self.tab_P300_Ring.setObjectName(_fromUtf8("tab_P300_Ring"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_P300_Ring)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ringDisplay = QtGui.QGraphicsView(self.tab_P300_Ring)
        self.ringDisplay.setObjectName(_fromUtf8("ringDisplay"))
        self.horizontalLayout_7.addWidget(self.ringDisplay)
        self.tabWidget.addTab(self.tab_P300_Ring, _fromUtf8(""))
        self.tab_About = QtGui.QWidget()
        self.tab_About.setObjectName(_fromUtf8("tab_About"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_About)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_About)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 956, 512))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textLog = QtGui.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textLog.setObjectName(_fromUtf8("textLog"))
        self.verticalLayout_4.addWidget(self.textLog)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8("lab_logo.png")))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_About, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BCI Control Panel", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton_Spin.setText(_translate("MainWindow", "Spin", None))
        self.pushButton_X.setText(_translate("MainWindow", "X", None))
        self.pushButton_Y.setText(_translate("MainWindow", "Y", None))
        self.pushButton_Z.setText(_translate("MainWindow", "Z", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Cube), _translate("MainWindow", "3D Cube", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Electrodes), _translate("MainWindow", "Electrodes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_EEG), _translate("MainWindow", "Signal", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SSVEP), _translate("MainWindow", "SSVEP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_P300_Ring), _translate("MainWindow", "P300 Ring", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>About BCI Control Panel</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_About), _translate("MainWindow", "About", None))

from EEGTab import EEGTab
from MyQGLWidget import MyQGLWidget
from SSVEPTab import SSVEPTab
from ElectrodeMap import ElectrodeMap
